'use strict';

function body(lang){
  const sr=lang==='sr';
  const field=(i,name,label,type='number',extra='')=>`<label>${label}<input name="${name}${i}" type="${type}" ${type==='number'?'min="0" step="any"':type==='url'?'maxlength="500"':'maxlength="120"'} ${extra}></label>`;
  const candidates=[0,1,2].map(i=>`<details class="card" ${i===0?'open':''}><summary>${sr?'Oglas':'Inserat'} ${i+1}</summary><div class="form" style="margin-top:16px">${field(i,'label',sr?'Marka i model':'Marke und Modell','text',i===0?'required':'')}${field(i,'link',sr?'Link oglasa (opciono)':'Inseratlink (optional)','url')}${field(i,'price',sr?'Cena auta (€)':'Kaufpreis (€)','number',i===0?'required':'')}${field(i,'transport',sr?'Dovoz do Srbije (€)':'Transport nach Serbien (€)')}${field(i,'export',sr?'Izvoz i tablice (€)':'Export und Kennzeichen (€)')}${field(i,'local',sr?'Špedicija, tehnički postupak i registracija (€)':'Abwicklung, Prüfung und Zulassung (€)')}${field(i,'year',sr?'Godište':'Baujahr','number')}${field(i,'euro',sr?'Euro norma (0 ako ne znaš)':'Euro-Norm (0 falls unbekannt)','number')}<label>${sr?'Dokaz o poreklu':'Ursprungsnachweis'}<select name="origin${i}"><option value="unknown">${sr?'Nije potvrđen':'Nicht bestätigt'}</option><option value="verified">${sr?'Potvrđen':'Bestätigt'}</option><option value="missing">${sr?'Nedostaje':'Fehlt'}</option></select></label><label class="check"><input type="checkbox" name="vin${i}">${sr?'VIN dostavljen':'VIN vorhanden'}</label><label class="check"><input type="checkbox" name="registration${i}">${sr?'Saobraćajna dostupna':'Zulassungsunterlagen vorhanden'}</label><label class="check"><input type="checkbox" name="ownership${i}">${sr?'Dokaz vlasništva dostupan':'Eigentumsnachweis vorhanden'}</label></div></details>`).join('');
  return `<section class="section"><p class="eyebrow">${sr?'PRE NEGO ŠTO KRENEŠ NA PUT':'VOR DER ANREISE'}</p><h1>${sr?'Koji oglas zaslužuje sledeću proveru?':'Welches Inserat lohnt den nächsten Prüfschritt?'}</h1><p class="lead">${sr?'Uporedi do tri auta iz Nemačke sa svojim ukupnim budžetom. Dobijaš računicu, nedostajuće podatke i pitanja za prodavca — na jednom mestu.':'Vergleiche bis zu drei Autos aus Deutschland mit deinem Gesamtbudget. Kosten, fehlende Angaben und Verkäuferfragen in einem Plan.'}</p><form id="buyer-plan"><div class="form">${field('','budget',sr?'Ukupan budžet do registracije (€)':'Gesamtbudget bis Zulassung (€)','number','required')}${field('','reserve',sr?'Tvoja rezerva za servis i nepredviđeno (€)':'Deine Reserve für Service und Unvorhergesehenes (€)','number','required')}<p class="muted wide">${sr?'Unesi svoje procene ili potvrđene ponude. Nula nije dokaz da troška nema: prazne ili nulte stavke ostaju označene kao neproverene. Rezerva se dodaje svakom autu.':'Eigene Schätzungen oder bestätigte Angebote eintragen. Leere oder nullwertige Kosten bleiben als ungeklärt markiert. Die Reserve wird bei jedem Auto ergänzt.'}</p></div><div style="display:grid;gap:16px;margin:20px 0">${candidates}</div><button class="btn" type="submit">${sr?'Napravi moj plan kupovine':'Meinen Kaufplan erstellen'}</button></form><div id="buyer-result" aria-live="polite"></div><p class="muted">${sr?'Poređenje koristi unete podatke; ne proverava oglas, VIN ili mehaničko stanje. Računica je procena, a carinski obračun i mogućnost uvoza moraju se potvrditi za konkretno vozilo. Linkovi oglasa ostaju u ovom pregledaču; kalkulatoru se šalju brojevi i označeni podaci.':'Der Vergleich nutzt deine Angaben und prüft weder Inserat noch VIN oder technischen Zustand. Kosten und Importfähigkeit müssen für das Fahrzeug bestätigt werden. Inseratlinks bleiben im Browser; der Rechner erhält Zahlen und ausgewählte Angaben.'}</p></section><section class="section"><h2>${sr?'Želiš da neko proveri tvoj izbor?':'Möchtest du deinen Vergleich prüfen lassen?'}</h2><p class="lead">${sr?'Zatraži ponudu za pregled do tri oglasa: pregled dostupnih podataka, pitanja prodavcu, razlike u ukupnom trošku i pisani pregled otvorenih rizika. Obim i cena se potvrđuju pre angažovanja; odgovor prodavca i stručni pregled nisu automatski uključeni.':'Angebot für bis zu drei Inserate anfragen: verfügbare Angaben, Verkäuferfragen, Kostenunterschiede und offene Risiken. Umfang und Preis vor Auftrag; Verkäuferantwort und technische Prüfung nicht automatisch enthalten.'}</p><a class="btn secondary" href="/${lang}/${sr?'upit':'anfrage'}?service=AD_REVIEW">${sr?'Zatraži proveru mog izbora':'Vergleich prüfen lassen'}</a></section>`;
}
module.exports={body};
