'use strict';

function body(lang){
  const sr=lang==='sr';
  const stages=sr?[
    ['Izbor i budžet','Tvoj ukupni budžet, namena i obavezni uslovi ostaju isti za svaki predlog. Uporedi i kupovinu sličnog auta u Srbiji.','Kupac + DANINI','Tabela kandidata, izvori i datum provere'],
    ['Prodavac i dokumenta','VIN na vozilu i dokumentima, identitet prodavca, pravo prodaje, račun ili ugovor, saobraćajna dokumenta i dokaz o poreklu. Nedostajući dokaz ostaje otvoren.','Prodavac + DANINI','Kopije dokumenata i pisani odgovori prodavca'],
    ['Pregled pre kupovine','Fotografije i video nisu mehanički pregled. Za tehničko stanje traži pisani nalaz nezavisnog stručnjaka, uz dogovoren obim.','Dogovoreni stručni saradnik','Nalaz, dijagnostika po dogovoru i otvoreni nedostaci'],
    ['Odluka i plaćanje','Pre kapare uskladi identitet primaoca, vozilo, cenu i uslove ugovora. Kupac odobrava kupovinu i plaća prema ugovoru.','Kupac + prodavac','Potpisan ugovor ili račun i dokaz plaćanja'],
    ['Izvoz i dovoz','Odaberi transporter ili vožnju nakon provere stanja, dokumenata, osiguranja i uslova rute. Izvozne dokumente i cenu potvrđuje izvršilac.','Izvozni saradnik + prevoznik','Pisana ponuda, dogovorena odgovornost i primopredaja'],
    ['Carina i poreklo','Kupovina u Nemačkoj ne dokazuje pravo na povlašćenu carinu. Špediter proverava dokumente i priprema obračun; carinski organ donosi konačnu odluku.','Špediter + carinski organ','Carinska dokumentacija i konačan obračun'],
    ['Ispitivanje i registracija','Za konkretno vozilo potvrdi dokumente i uslove kod ovlašćenog ispitnog mesta pre kupovine. Ispitivanje, tehnički pregled i registracija su odvojeni koraci.','Ovlašćeno ispitno mesto + registraciona služba','Uverenje, tehnički pregled, osiguranje i registracija'],
    ['Primopredaja i prvi servis','Uporedi primljeno vozilo sa ugovorom i nalazom, zabeleži nedostatke i sačuvaj dokaze. Servisnu rezervu planiraj prema stručnom nalazu.','Kupac + servis','Zapisnik i plan prvog servisa']
  ]:[
    ['Auswahl und Budget','Gesamtbudget und Muss-Kriterien gelten für jeden Vorschlag. Auch einen vergleichbaren Kauf in Serbien berücksichtigen.','Käufer + DANINI','Kandidaten, Quellen und Prüfdatum'],
    ['Verkäufer und Dokumente','VIN, Verkäufer, Verkaufsberechtigung, Rechnung oder Vertrag, Zulassungsunterlagen und Ursprungsnachweis abgleichen.','Verkäufer + DANINI','Unterlagen und schriftliche Antworten'],
    ['Prüfung vor Kauf','Fotos ersetzen keine technische Prüfung. Umfang und schriftlichen Befund mit einem unabhängigen Fachpartner vereinbaren.','Vereinbarter Fachpartner','Befund und offene Mängel'],
    ['Entscheidung und Zahlung','Empfänger, Fahrzeug, Preis und Vertragsbedingungen vor Anzahlung abgleichen. Der Käufer genehmigt den Kauf.','Käufer + Verkäufer','Vertrag oder Rechnung und Zahlungsbeleg'],
    ['Export und Transport','Transporter oder eigene Achse nach Zustand, Papieren, Versicherung und Route wählen. Angebot und Exportunterlagen bestätigen lassen.','Exportpartner + Transporteur','Angebot und Übergabeprotokoll'],
    ['Zoll und Ursprung','Kauf in Deutschland beweist keinen Präferenzursprung. Ein Zollpartner prüft; die Behörde entscheidet abschließend.','Zollpartner + Behörde','Zolldokumente und Abrechnung'],
    ['Prüfung und Zulassung','Anforderungen vor Kauf am konkreten Fahrzeug klären. Importprüfung, technische Prüfung und Zulassung sind getrennte Schritte.','Autorisierte Prüfstelle + Zulassungsstelle','Bescheinigungen und Zulassung'],
    ['Übergabe und Service','Fahrzeug mit Vertrag und Befund abgleichen, Abweichungen dokumentieren und Servicebudget nach Fachbefund planen.','Käufer + Werkstatt','Übergabeprotokoll und Serviceplan']
  ];
  const input=(name,label,type='text')=>`<label>${label}<input name="${name}" type="${type}" ${type==='number'?'min="1" step="1"':'maxlength="300"'} required></label>`;
  return `<section class="section"><p class="eyebrow">${sr?'OD IZBORA DO REGISTRACIJE':'VON DER AUSWAHL BIS ZUR ZULASSUNG'}</p><h1>${sr?'Tvoj dosije kupovine i uvoza':'Dein Kauf- und Importdossier'}</h1><p class="lead">${sr?'Jedan zahtev, isti uslovi za sve automobile i jasan sledeći korak. Počni od svog problema; svaki angažman potvrđujemo zasebnom ponudom.':'Eine Anfrage, gleiche Kriterien für alle Fahrzeuge und ein klarer nächster Schritt. Jeder Auftrag wird separat bestätigt.'}</p><form id="purchase-brief" class="form">${input('budget',sr?'Ukupan budžet do registracije (€)':'Gesamtbudget bis Zulassung (€)','number')}${input('criteria',sr?'Obavezni uslovi: motor, menjač, godište, kilometraža, oprema':'Muss-Kriterien: Motor, Getriebe, Baujahr, Laufleistung, Ausstattung')}${input('purpose',sr?'Namena vozila i mesto registracije':'Nutzung und Zulassungsort')}<label>${sr?'Gde si sada?':'Aktueller Schritt'}<select name="stage">${stages.map((s,i)=>`<option value="${i}">${i+1}. ${s[0]}</option>`).join('')}</select></label><label class="wide">${sr?'Oglas i šta ti nedostaje (bez ličnih dokumenata)':'Inserat und offene Fragen (keine persönlichen Dokumente)'}<textarea name="details" rows="4" maxlength="2000" required></textarea></label><button class="btn wide" type="submit">${sr?'Pripremi zahtev za moj sledeći korak':'Anfrage für meinen nächsten Schritt vorbereiten'}</button></form><div id="purchase-result" aria-live="polite"></div><p class="muted">${sr?'Ovaj obrazac priprema zahtev; ne proverava auto i ne rezerviše partnera. Podaci se šalju tek kada na sledećoj stranici potvrdiš upit.':'Das Formular bereitet eine Anfrage vor; es prüft kein Fahrzeug und bucht keinen Partner. Versand erst nach Bestätigung auf der nächsten Seite.'}</p></section><section class="section"><h2>${sr?'Šta rešavamo u svakom koraku':'Aufgaben pro Schritt'}</h2><div class="grid">${stages.map((s,i)=>`<article class="card"><span class="eyebrow">${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p><p><strong>${sr?'Izvršilac':'Verantwortlich'}:</strong> ${s[2]}</p><p><strong>${sr?'Dokaz za dosije':'Beleg'}:</strong> ${s[3]}</p></article>`).join('')}</div><p class="muted">${sr?'Dostupnost saradnika, obim, troškovi i rokovi nisu potvrđeni ovim prikazom. Konačna mogućnost uvoza zavisi od vozila, dokumentacije i nadležnih postupaka.':'Partnerverfügbarkeit, Umfang, Kosten und Termine werden gesondert bestätigt. Importfähigkeit hängt von Fahrzeug, Unterlagen und behördlichen Verfahren ab.'}</p><p><a href="/${lang}/${sr?'uporedi-oglase':'inserate-vergleichen'}">${sr?'Uporedi troškove kandidata':'Kandidatenkosten vergleichen'} →</a></p><p>${sr?'Zvanični izvori':'Offizielle Quellen'}: <a href="https://www.carina.rs/putnici/pitanja-i-odgovori/uvoz-polovnih-vozila.html">Uprava carina</a> · <a href="https://abs.gov.rs/rsc/uvozupotrebljavanihvozilapostupak">ABS</a></p></section>`;
}
module.exports={body};
