import './BusinessPages.css'

const pages={
 de:{
  '/de/leistungsrahmen':{k:'ZUSAMMENARBEIT',t:'Klarer Leistungsrahmen. Flexible operative Unterstützung.',lead:'DaniniHub unterstützt Transportteams in einem schriftlich vereinbarten Rahmen. Aufgaben können modular ergänzt werden, ohne Zuständigkeiten, Preise oder rechtsverbindliche Entscheidungen des Auftraggebers zu übernehmen.',blocks:[['Direkt unterstützbar',['Status- und ETA-Nachverfolgung','Mehrsprachige Fahrerkommunikation','Dokumenten- und Informationskontrolle','Abweichungen strukturiert aufnehmen','Entscheidungen vorbereiten und eskalieren','Schichtübergaben und operative Berichte']],['Nur mit schriftlicher Freigabe',['Kontakt mit Lade- und Entladestellen','Arbeit in TMS, Portalen oder Funktionspostfächern','Kommunikation im Namen des Unternehmens','Terminabstimmung innerhalb definierter Regeln','Recherche nach Rückladung oder Ersatzkapazität']],['Bleibt beim Auftraggeber',['Preise und Vertragsabschluss','Transportauftrag und finale Disposition','Rechtsverbindliche Zusagen','Verkehrsleitung, Zoll- und Rechtsberatung','Freigabe zusätzlicher Kosten und Partnerauswahl']]],cta:'Pilot-Check starten'},
  '/de/continuity-support':{k:'CONTINUITY SUPPORT',t:'Wenn Kapazität fehlt, darf die operative Kontrolle nicht ausfallen.',lead:'Begrenzte Unterstützung bei Urlaub, Krankheit, Spitzenlast, Einarbeitung oder fehlender Abendkapazität – ergänzend zum bestehenden Team und System.',blocks:[['Typische Einsatzfälle',['Urlaubs- und Krankheitsvertretung für definierte Aufgaben','Abendliche Status- und ETA-Kontrolle','Unterstützung bei erhöhtem Transportvolumen','Dokumentierte Übergabe offener Vorgänge','Begleitung einer Relation oder Fahrzeuggruppe']],['So beginnt die Zusammenarbeit',['Engpass und Zeitraum klären','Aufgaben, Zugänge und Freigaben schriftlich festlegen','Mit kleiner Fahrzeuggruppe oder Relation starten','Reaktionszeiten und Erfolgskriterien vereinbaren','Pilotprojekt auswerten und Umfang nur bei Bedarf erweitern']]],cta:'Continuity-Pilot prüfen'},
  '/de/fahrerkommunikation':{k:'BALKAN–DACH COMMUNICATION',t:'Mehrsprachige operative Begleitung für Fahrer und Disposition.',lead:'DaniniHub hilft, dass Anweisungen, Statusmeldungen und Probleme zwischen Fahrern aus dem Balkanraum und deutschsprachigen Transportteams korrekt verstanden, bestätigt und dokumentiert werden.',blocks:[['Vor und während der Tour',['Adresse, Referenz, Zeitfenster und Ansprechpartner klären','Kritische Anweisungen verständlich erklären','Vereinbarte Statuspunkte und ETA nachverfolgen','Probleme bei Beladung, Entladung, Wartezeit oder Störung strukturieren','Antworten auf Deutsch vorbereiten und verständlich zurückgeben']],['Wichtige Grenze',['Keine eigenständige Änderung von Route, Termin oder Preis','Keine Zusage zusätzlicher Kosten ohne Freigabe','Keine Arbeitnehmerüberlassung oder Arbeitsvermittlung','Entscheidungen verbleiben beim Auftraggeber']]],cta:'Fahrerbegleitung anfragen'}
 },
 sr:{
  '/sr/obim-usluge':{k:'SARADNJA',t:'Jasan obim usluge. Fleksibilna operativna podrška.',lead:'DaniniHub podržava transportne timove u pismeno dogovorenom okviru. Obim se može modularno proširivati bez preuzimanja odgovornosti za cene, ugovaranje ili konačne odluke naručioca.',blocks:[['Direktno podržavamo',['Praćenje statusa i ETA','Višejezička komunikacija sa vozačima','Kontrola dokumenata i informacija','Strukturisanje odstupanja','Priprema zahteva za odluku i eskalacija','Predaja smene i operativni izveštaji']],['Samo uz pisano ovlašćenje',['Kontakt sa mestima utovara i istovara','Rad u TMS-u, portalima ili zajedničkom e-mail sandučetu','Komunikacija u ime kompanije','Dogovor termina u definisanim granicama','Istraživanje povratnog tereta ili zamenskog kapaciteta']],['Ostaje kod naručioca',['Cene i zaključivanje ugovora','Transportni nalog i konačna dispozicija','Pravno obavezujuća obećanja','Rukovođenje transportom, carinski i pravni saveti','Odobrenje dodatnih troškova i izbor partnera']]],cta:'Pokreni proveru pilota'},
  '/sr/kontinuitet-podrska':{k:'PODRŠKA KONTINUITETU',t:'Kada nedostaje kapacitet, operativna kontrola ne sme da stane.',lead:'Ograničena podrška tokom odmora, bolovanja, povećanog obima, uvođenja novog radnika ili nedostatka večernjeg kapaciteta.',blocks:[['Tipične situacije',['Zamena za jasno definisane zadatke','Večernja kontrola statusa i ETA','Podrška pri povećanom obimu transporta','Dokumentovana predaja otvorenih slučajeva','Praćenje jedne relacije ili grupe vozila']],['Kako počinjemo',['Definišemo problem i period','Pismeno utvrđujemo zadatke, pristupe i odobrenja','Počinjemo malom grupom vozila ili jednom relacijom','Dogovaramo vreme reakcije i kriterijume uspeha','Širimo obim samo nakon evaluacije']]],cta:'Proveri pilot kontinuiteta'},
  '/sr/komunikacija-vozaci':{k:'BALKAN–DACH KOMUNIKACIJA',t:'Višejezička operativna podrška vozačima i dispoziciji.',lead:'DaniniHub pomaže da instrukcije, statusi i problemi između vozača sa Balkana i nemačkih transportnih timova budu pravilno shvaćeni, potvrđeni i dokumentovani.',blocks:[['Pre i tokom ture',['Razjašnjenje adrese, reference, termina i kontakata','Objašnjenje kritičnih instrukcija razumljivim jezikom','Praćenje dogovorenih statusa i ETA','Strukturisanje problema na utovaru, istovaru, čekanju ili kod kvara','Priprema nemačke poruke i prenos odgovora vozaču']],['Važne granice',['Bez samostalne promene rute, termina ili cene','Bez prihvatanja dodatnih troškova bez odobrenja','Bez ustupanja radnika ili posredovanja pri zapošljavanju','Konačne odluke ostaju kod naručioca']]],cta:'Pošalji upit za podršku vozačima'}
 }
}

export default function BusinessPages({lang}){const p=pages[lang][location.pathname];if(!p)return null;const check=lang==='sr'?'/sr/provera-pilota':'/de/pilot-check';return <main className="bp-shell"><header className="bp-head"><a href={lang==='sr'?'/sr/':'/de/'}>← DaniniHub</a><strong>TRANSPORT &amp; LOGISTICS</strong></header><article className="bp-page"><p className="kicker">{p.k}</p><h1>{p.t}</h1><p className="bp-lead">{p.lead}</p><div className="bp-grid">{p.blocks.map(([h,items])=><section key={h}><h2>{h}</h2><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section>)}</div><div className="bp-cta"><a className="btn" href={check}>{p.cta} →</a><a href={lang==='sr'?'/sr/#contact':'/de/#contact'}>{lang==='sr'?'Direktan kontakt':'Direkter Kontakt'} →</a></div></article></main>}
