import './Enhancements.css'
import './Content.css'

const sources = {
  balm: 'https://www.balm.bund.de/DE/Themen/Genehmigungen/Marktzugangsverfahren/GewerblicherGueterverkehr/gewerblichergueterverkehr_node.html',
  driving: 'https://eur-lex.europa.eu/eli/reg/2006/561/2024-12-31/eng',
  tachograph: 'https://eur-lex.europa.eu/EN/legal-content/summary/tachographs-in-road-transport.html',
  tachograph2026: 'https://transport.ec.europa.eu/transport-modes/road/tachograph_en',
  posting: 'https://transport.ec.europa.eu/transport-modes/road/mobility-package-i/posting-rules/questions-and-answers-posting-drivers-under-directive-eu-20201057_en',
  efti: 'https://transport.ec.europa.eu/transport-themes/logistics-and-multimodal-transport/efti-regulation_en',
  working: 'https://eur-lex.europa.eu/EN/legal-content/summary/road-transport-eu-rules-on-the-organisation-of-the-working-time-of-professional-drivers.html',
  gdpr: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj'
}

const glossary = [
  ['Auftraggeber','naručilac','Firma koja daje nalog ili ugovara uslugu.'],['Frachtführer','prevoznik','Firma koja ugovorno obavlja prevoz robe.'],['Spediteur','špediter','Organizuje otpremu i može ugovarati druge izvršioce.'],['Disponent','disponent','Koordinira vozila, vozače, termine i informacije.'],['Verkehrsleiter','rukovodilac transporta','Zakonski odgovorna stručna osoba prevoznika; DaniniHub ne preuzima ovu ulogu.'],['Transportauftrag','transportni nalog','Dokument sa rutom, robom, terminima, cenom i uslovima.'],['Frachtbrief / CMR','tovarni list / CMR','Dokument međunarodnog drumskog prevoza.'],['POD / Abliefernachweis','dokaz isporuke','Potvrda da je roba predata primaocu.'],['Ladestelle','mesto utovara','Lokacija na kojoj se roba preuzima.'],['Entladestelle','mesto istovara','Lokacija na kojoj se roba isporučuje.'],['Zeitfenster / Slot','termin','Dogovoreni vremenski period za utovar ili istovar.'],['ETA','očekivano vreme dolaska','Procena kada vozilo stiže.'],['Statusmeldung','statusna informacija','Kratka proverljiva informacija o toku ture.'],['Abweichung','odstupanje','Razlika između plana i stvarnog toka.'],['Standzeit','vreme čekanja','Vreme kada vozilo čeka bez vožnje ili obrade.'],['Leerfahrt','prazna vožnja','Vožnja bez tereta.'],['Rückladung','povratni teret','Teret organizovan za povratnu relaciju.'],['FTL','pun kamion','Pošiljka koristi čitav ili najveći deo vozila.'],['LTL / Teilladung','delimični teret','Pošiljka deli kapacitet vozila sa drugom robom.'],['Lademeter','utovarni metar','Dužinski deo poda vozila koji zauzima roba.'],['Nutzlast','korisna nosivost','Masa tereta koju vozilo sme da prevozi u dozvoljenim granicama.'],['Lenkzeit','vreme vožnje','Vreme evidentirano kao upravljanje vozilom.'],['Ruhezeit','vreme odmora','Zakonom propisan period odmora vozača.'],['Tachograph','tahograf','Uređaj koji evidentira aktivnosti vozila i vozača.'],['Gemeinschaftslizenz','licenca Zajednice','Dozvola za određeni komercijalni međunarodni drumski prevoz u EU.'],['Kabotage','kabotaža','Unutrašnji prevoz u državi članici koji obavlja strani prevoznik pod propisanim uslovima.'],['Fahrerentsendung','upućivanje vozača','Primena pravila o upućivanju kod određenih prekograničnih transportnih operacija.'],['Zollabfertigung','carinjenje','Postupak prijave robe carinskim organima.'],['MRN','referentni broj carinskog postupka','Jedinstveni broj za praćenje carinske deklaracije ili postupka.'],['T1','tranzitni dokument','Dokument za kretanje neocarinjene robe u zajedničkom tranzitnom postupku.'],['ADR','opasna roba','Evropski sporazum i operativna oznaka za drumski prevoz opasne robe.'],['Eskalation','eskalacija','Prosleđivanje problema odgovornoj osobi radi odluke.']
]

function Shell({ lang, title, children }) {
  return <main className="content-shell"><header className="content-head"><a href={lang==='sr'?'/sr/':'/de/'}>← DaniniHub</a><strong>Transport &amp; Logistics</strong></header><article className="content-page"><p className="kicker">{lang==='sr'?'INFORMACIJE':'INFORMATION'}</p><h1>{title}</h1>{children}</article></main>
}

function Privacy({lang}) {
  const sr=lang==='sr'
  return <Shell lang={lang} title={sr?'Zaštita podataka i GDPR':'Datenschutzerklärung'}><p className="updated">{sr?'Stanje':'Stand'}: 17.07.2026</p>
    <h2>{sr?'1. Odgovorno lice':'1. Verantwortlicher'}</h2><p>Dragan Zdravković · DaniniHub Transport &amp; Logistics · Fischerstraße 54 · 47055 Duisburg · <a href="mailto:info@daninihub.com">info@daninihub.com</a> · <a href="tel:+4915730916621">+49 1573 0916621</a></p>
    <h2>{sr?'2. Podaci koje obrađujemo':'2. Verarbeitete Daten'}</h2><p>{sr?'Kod upita obrađujemo firmu/ime, e-mail, dobrovoljno telefon, broj vozila i relacije, izabrano interesovanje, tekst poruke, vreme prijema i tehničke serverske zapise.':'Bei Anfragen verarbeiten wir Unternehmen/Name, E-Mail, freiwillig Telefon, Fahrzeugzahl und Relationen, gewähltes Interesse, Nachrichtentext, Eingangszeit und technische Serverprotokolle.'}</p>
    <h2>{sr?'3. Svrha i pravni osnov':'3. Zwecke und Rechtsgrundlagen'}</h2><p>{sr?'Podaci služe odgovoru na upit, pripremi razgovora ili ponude, sprečavanju zloupotrebe i bezbednom radu sajta. Osnov su čl. 6 st. 1 tač. b GDPR (predugovorne mere), tač. f (bezbednost i legitimna poslovna komunikacija) i, gde je primenljivo, tač. a (saglasnost).':'Die Daten dienen der Beantwortung, Gesprächs- oder Angebotsvorbereitung, Missbrauchsabwehr und dem sicheren Websitebetrieb. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO (vorvertragliche Maßnahmen), lit. f (Sicherheit und legitime Geschäftskommunikation) sowie, soweit einschlägig, lit. a (Einwilligung).'}</p>
    <h2>{sr?'4. Brevo i primaoci':'4. Brevo und Empfänger'}</h2><p>{sr?'Brevo se koristi za slanje internog obaveštenja i automatske potvrde. Podaci se ne dodaju na newsletter listu. Hosting i e-mail provajderi dobijaju podatke samo koliko je tehnički potrebno. Sa pružaocima se zaključuju odgovarajući ugovori o obradi podataka.':'Brevo wird für die interne Benachrichtigung und automatische Eingangsbestätigung eingesetzt. Eine Aufnahme in Newsletterlisten erfolgt nicht. Hosting- und E-Mail-Dienstleister erhalten Daten nur soweit technisch erforderlich; erforderliche Auftragsverarbeitungsverträge werden abgeschlossen.'}</p>
    <h2>{sr?'5. Rok čuvanja':'5. Speicherdauer'}</h2><p>{sr?'Upiti bez ugovora brišu se najkasnije 12 meseci nakon završetka komunikacije, osim ako pravna obaveza, zahtev ili odbrana prava zahteva duže čuvanje. Ugovorna i računovodstvena dokumentacija čuva se prema zakonskim rokovovima.':'Anfragen ohne Vertrag werden spätestens 12 Monate nach Abschluss der Kommunikation gelöscht, sofern keine Rechts-, Nachweis- oder Verteidigungsgründe entgegenstehen. Vertrags- und Buchhaltungsunterlagen unterliegen gesetzlichen Fristen.'}</p>
    <h2>{sr?'6. Vaša prava':'6. Betroffenenrechte'}</h2><p>{sr?'Imate pravo na pristup, ispravku, brisanje, ograničenje, prenosivost, prigovor i povlačenje saglasnosti za budućnost, kao i pritužbu nadležnom organu.':'Sie haben Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Widerruf für die Zukunft sowie Beschwerde bei einer Aufsichtsbehörde.'}</p>
    <h2>{sr?'7. Bez automatizovanog odlučivanja':'7. Keine automatisierte Entscheidung'}</h2><p>{sr?'Upiti se ne koriste za automatizovano odlučivanje ili profilisanje.':'Anfragen werden nicht für automatisierte Entscheidungen oder Profiling verwendet.'}</p><p className="source-note"><a href={sources.gdpr} target="_blank" rel="noreferrer">EU GDPR / DSGVO</a></p>
  </Shell>
}

function Cookies({lang}) { const sr=lang==='sr'; return <Shell lang={lang} title={sr?'Kolačići i lokalno čuvanje':'Cookies und lokale Speicherung'}><p className="updated">{sr?'Stanje':'Stand'}: 17.07.2026</p><h2>{sr?'Trenutno stanje':'Aktueller Einsatz'}</h2><p>{sr?'DaniniHub trenutno ne postavlja reklamne, analitičke niti tracking kolačiće. Nema Google Analytics, Meta Pixel, ugrađenih mapa ili marketinških videa.':'DaniniHub setzt derzeit keine Werbe-, Analyse- oder Tracking-Cookies ein. Es werden kein Google Analytics, Meta Pixel, eingebettete Karten oder Marketingvideos verwendet.'}</p><h2>Local Storage</h2><p>{sr?'Pregledač može lokalno zapamtiti samo da je informacija o kolačićima pročitana. Taj podatak ne sadrži ime, e-mail ili identifikacioni profil i ne šalje se DaniniHub-u.':'Der Browser kann lokal speichern, dass der Cookie-Hinweis gelesen wurde. Diese Information enthält keinen Namen, keine E-Mail und kein Nutzerprofil und wird nicht an DaniniHub übertragen.'}</p><h2>{sr?'Buduće izmene':'Künftige Änderungen'}</h2><p>{sr?'Ako se kasnije uvedu neobavezne analitičke ili marketinške tehnologije, one neće biti aktivirane pre saglasnosti i ova stranica će biti ažurirana.':'Werden später optionale Analyse- oder Marketingtechnologien eingeführt, werden sie nicht vor einer Einwilligung aktiviert und diese Seite wird aktualisiert.'}</p></Shell> }

function Disclaimer({lang}) { const sr=lang==='sr'; return <Shell lang={lang} title={sr?'Odricanje odgovornosti i granice sadržaja':'Haftungsausschluss und Inhaltsgrenzen'}><p className="updated">{sr?'Stanje':'Stand'}: 17.07.2026</p><h2>{sr?'Informativni sadržaj':'Informationsangebot'}</h2><p>{sr?'Sadržaj sajta, procedure, rečnik i linkovi služe opštoj operativnoj orijentaciji. Ne predstavljaju pravno, poresko, carinsko, bezbednosno niti stručno savetovanje za konkretan slučaj.':'Websiteinhalte, Verfahren, Glossar und Links dienen der allgemeinen operativen Orientierung. Sie sind keine Rechts-, Steuer-, Zoll-, Sicherheits- oder Einzelfallberatung.'}</p><h2>{sr?'Promene propisa':'Rechtsänderungen'}</h2><p>{sr?'Transportni propisi i službena tumačenja se menjaju. Merodavni su važeći tekst propisa, službena uputstva, ugovor i odluka odgovornog lica firme.':'Transportvorschriften und Behördenhinweise ändern sich. Maßgeblich sind geltendes Recht, amtliche Hinweise, Vertrag und die Entscheidung der verantwortlichen Stelle im Unternehmen.'}</p><h2>{sr?'Operativna odgovornost':'Operative Verantwortung'}</h2><p>{sr?'DaniniHub ne preuzima ulogu prevoznika, špeditera, Verkehrsleitera, carinskog zastupnika niti poslodavca vozača. Nalozi, cene, pravno obavezujuća obećanja, vozačke instrukcije i konačne odluke ostaju kod naručioca.':'DaniniHub übernimmt nicht die Rolle von Frachtführer, Spediteur, Verkehrsleiter, Zollvertreter oder Arbeitgeber des Fahrers. Aufträge, Preise, rechtsverbindliche Zusagen, Fahrerweisungen und finale Entscheidungen verbleiben beim Auftraggeber.'}</p><h2>{sr?'Spoljni linkovi':'Externe Links'}</h2><p>{sr?'Za sadržaj službenih i drugih spoljnih stranica odgovorni su njihovi operatori. Linkovi se proveravaju pri objavljivanju, ali ne postoji stalna kontrola svih izmena.':'Für Inhalte externer Seiten sind deren Betreiber verantwortlich. Links werden bei Veröffentlichung geprüft; eine permanente Kontrolle sämtlicher Änderungen erfolgt nicht.'}</p></Shell> }

function Practice({lang}) { const sr=lang==='sr'; return <Shell lang={lang} title={sr?'Osnovne procedure i propisi':'Grundverfahren und Vorschriften'}><p className="warning">{sr?'Operativna kontrolna lista, ne pravni savet. Uvek proveriti nalog, interne procedure firme i aktuelne službene izvore.':'Operative Checkliste, keine Rechtsberatung. Auftrag, interne Unternehmensprozesse und aktuelle amtliche Quellen stets prüfen.'}</p>
  <h2>{sr?'1. Pre prihvatanja zadatka':'1. Vor Aufgabenübernahme'}</h2><ol><li>{sr?'Identifikovati naručioca i odgovornu osobu.':'Auftraggeber und verantwortliche Person feststellen.'}</li><li>{sr?'Potvrditi relaciju, vozilo, robu, težinu, termine i kontakt mesta.':'Relation, Fahrzeug, Ware, Gewicht, Termine und Stellenkontakte bestätigen.'}</li><li>{sr?'Zabeležiti šta DaniniHub sme da potvrdi, a šta mora da eskalira.':'Dokumentieren, was DaniniHub bestätigen darf und was eskaliert werden muss.'}</li></ol>
  <h2>{sr?'2. Tok ture':'2. Tourablauf'}</h2><ol><li>{sr?'Prijem proverljivog statusa od vozača ili sistema.':'Prüfbaren Status vom Fahrer oder System aufnehmen.'}</li><li>{sr?'Uporediti planirani termin i ETA.':'Plantermin und ETA vergleichen.'}</li><li>{sr?'Kod odstupanja navesti činjenicu, posledicu, sledeću proveru i osobu koja odlučuje.':'Bei Abweichung Tatsache, Auswirkung, nächste Prüfung und Entscheider nennen.'}</li><li>{sr?'Sačuvati trag komunikacije.':'Kommunikationsnachweis sichern.'}</li></ol>
  <h2>{sr?'3. Dokumenti':'3. Dokumente'}</h2><p>{sr?'U zavisnosti od ture proveravaju se transportni nalog, CMR/tovarni list, podaci o robi, registarske oznake, potvrde utovara/istovara i carinski dokumenti. DaniniHub proverava operativnu potpunost, ne pravnu ispravnost.':'Je nach Tour werden Transportauftrag, CMR/Frachtbrief, Warenangaben, Kennzeichen, Lade-/Abliefernachweise und Zolldokumente auf operative Vollständigkeit geprüft – nicht rechtsverbindlich bewertet.'}</p>
  <h2>{sr?'4. Ključni propisi za proveru':'4. Wichtige Regelwerke zur Prüfung'}</h2><ul className="law-list"><li><a href={sources.driving} target="_blank" rel="noreferrer">VO (EG) 561/2006</a> – {sr?'vreme vožnje, pauze i odmori':'Lenkzeiten, Pausen und Ruhezeiten'}</li><li><a href={sources.tachograph} target="_blank" rel="noreferrer">VO (EU) 165/2014</a> – {sr?'tahografi':'Fahrtenschreiber'}</li><li><a href={sources.working} target="_blank" rel="noreferrer">RL 2002/15/EG</a> – {sr?'radno vreme mobilnih radnika':'Arbeitszeit mobiler Arbeitnehmer'}</li><li><a href={sources.balm} target="_blank" rel="noreferrer">BALM</a> – {sr?'dozvole i pristup tržištu u Nemačkoj':'Genehmigungen und Marktzugang in Deutschland'}</li></ul>
  <h2>{sr?'5. Aktuelne i najavljene promene':'5. Aktuelle und kommende Änderungen'}</h2><div className="update-grid"><section><strong>{sr?'Od 1. jula 2026.':'Seit 1. Juli 2026'}</strong><p>{sr?'Za vozila ili kombinacije vozila preko 2,5 t do 3,5 t koja obavljaju međunarodni komercijalni prevoz robe ili kabotažu primenjuju se EU pravila o vremenu vožnje i odmora; potreban je smart tahograf verzije 2. Proveriti konkretan slučaj i izuzetke u zvaničnim izvorima.':'Für Fahrzeuge oder Fahrzeugkombinationen über 2,5 t bis 3,5 t im grenzüberschreitenden gewerblichen Güterverkehr oder in der Kabotage gelten die EU-Lenk- und Ruhezeitregeln; ein intelligenter Fahrtenschreiber Version 2 ist erforderlich. Einzelfall und Ausnahmen amtlich prüfen.'}</p><a href={sources.tachograph2026} target="_blank" rel="noreferrer">EU-Kommission: Tachograph</a></section><section><strong>{sr?'Od 9. jula 2027.':'Ab 9. Juli 2027'}</strong><p>{sr?'Po uredbi eFTI, nadležni organi država članica moraju prihvatati propisane elektronske informacije o teretnom transportu kada se dostavljaju preko sertifikovane eFTI platforme. To nije opšta obaveza firmi da odmah napuste papirnu dokumentaciju.':'Nach der eFTI-Verordnung müssen Behörden der Mitgliedstaaten vorgeschriebene elektronische Güterverkehrsinformationen akzeptieren, wenn sie über eine zertifizierte eFTI-Plattform bereitgestellt werden. Daraus folgt keine allgemeine Pflicht für Unternehmen, Papier sofort abzuschaffen.'}</p><a href={sources.efti} target="_blank" rel="noreferrer">EU-Kommission: eFTI</a></section></div>
  <p className="source-note">{sr?'Za upućivanje vozača i IMI prijave proveriti vrstu konkretne operacije.':'Bei Fahrerentsendung und IMI-Meldungen ist die konkrete Beförderungsart zu prüfen.'} <a href={sources.posting} target="_blank" rel="noreferrer">EU-Kommission: Fahrerentsendung</a></p>
  <h2>{sr?'6. Incident i eskalacija':'6. Störung und Eskalation'}</h2><p>{sr?'Kod nezgode, kvara, odbijanja robe, sumnje u dokumenta, prekoračenja vremena, carinskog problema ili zahteva za promenu cene: ne obećavati rešenje bez ovlašćenja; obezbediti činjenice, vreme, kontakt i odmah uključiti odgovornu osobu firme.':'Bei Unfall, Panne, Warenverweigerung, Dokumentenzweifel, Zeitverstoß, Zollproblem oder Preisänderung nichts ohne Befugnis zusagen; Fakten, Zeitpunkt und Kontakt sichern und sofort die verantwortliche Unternehmensperson einschalten.'}</p>
  <p className="updated">{sr?'Poslednja sadržajna provera':'Letzte inhaltliche Prüfung'}: 17.07.2026</p>
  </Shell> }

function Glossary({lang}) { const sr=lang==='sr'; return <Shell lang={lang} title={sr?'DE–SR rečnik transportnih izraza':'DE–SR Transportglossar'}><p>{sr?'Praktični izrazi za komunikaciju u dispečingu. Objašnjenja su operativna, ne pravne definicije.':'Praktische Begriffe für die Dispositionskommunikation. Die Erklärungen sind operativ und keine Rechtsdefinitionen.'}</p><div className="glossary">{glossary.map(([de,term,desc])=><section key={de}><h2>{de}</h2><strong>{term}</strong><p>{desc}</p></section>)}</div></Shell> }

export default function LegalKnowledge({lang,path}){if(/datenschutz|privatnost/.test(path))return <Privacy lang={lang}/>;if(/cookies|kolacici/.test(path))return <Cookies lang={lang}/>;if(/haftungsausschluss|odricanje-odgovornosti/.test(path))return <Disclaimer lang={lang}/>;if(/praxis-wissen|praksa-propisi/.test(path))return <Practice lang={lang}/>;return <Glossary lang={lang}/>}
