import './RevenueOSLanding.css'

export default function RevenueLegal({ lang='de', type='imprint' }){
  const sr=lang==='sr'
  const title = type==='privacy' ? (sr?'Privatnost':'Datenschutz') : type==='disclaimer' ? (sr?'AI transparentnost i granice':'AI-Transparenz und Grenzen') : (sr?'Impresum':'Impressum')
  return <div className="ros"><header className="ros-header"><a className="ros-brand" href={`/${lang}/`}><span className="ros-mark">D</span><span><strong>DaniniHub</strong><small>Human + AI Revenue OS</small></span></a></header><main className="ros-section" style={{maxWidth:'900px'}}>
    <p className="ros-eyebrow">LEGAL & TRUST</p><h1 style={{fontSize:'clamp(42px,6vw,68px)',letterSpacing:'-.04em'}}>{title}</h1>
    {type==='imprint' && <><h2 style={{fontSize:'28px',marginTop:'38px'}}>{sr?'Pružalac usluge':'Diensteanbieter'}</h2><p>Dragan Zdravković<br/>DaniniHub<br/>Fischerstraße 54<br/>47055 Duisburg · Deutschland<br/><a href="mailto:info@daninihub.com">info@daninihub.com</a></p><p>{sr?'DaniniHub pruža digitalne poslovne, istraživačke i automatizacione usluge. Konkretan obim, cena i odgovornost definišu se pre plaćenog angažmana.':'DaniniHub bietet digitale Geschäfts-, Research- und Automatisierungsleistungen. Konkreter Umfang, Preis und Verantwortung werden vor einem bezahlten Auftrag festgelegt.'}</p></>}
    {type==='privacy' && <><h2 style={{fontSize:'28px',marginTop:'38px'}}>{sr?'Obrada podataka':'Datenverarbeitung'}</h2><p>{sr?'Podaci iz kontakt obrasca obrađuju se radi odgovora na upit i procene odgovarajućeg sledećeg koraka. Za slanje potvrda i poslovne email komunikacije može se koristiti Brevo. Hosting provajder može obrađivati tehnički neophodne serverske zapise. Podaci se ne koriste za newsletter bez posebne saglasnosti.':'Formulardaten werden zur Bearbeitung der Anfrage und zur Prüfung eines geeigneten nächsten Schritts verarbeitet. Für Bestätigungen und geschäftliche E-Mail-Kommunikation kann Brevo eingesetzt werden. Der Hosting-Anbieter kann technisch notwendige Serverprotokolle verarbeiten. Eine Newsletter-Nutzung erfolgt nicht ohne gesonderte Einwilligung.'}</p><p>{sr?'Možete tražiti pristup, ispravku, brisanje ili ograničenje obrade u zakonskom okviru preko info@daninihub.com.':'Im gesetzlichen Rahmen können Sie Auskunft, Berichtigung, Löschung oder Einschränkung der Verarbeitung über info@daninihub.com verlangen.'}</p></>}
    {type==='disclaimer' && <><h2 style={{fontSize:'28px',marginTop:'38px'}}>{sr?'Kako koristimo AI':'Wie wir KI einsetzen'}</h2><p>{sr?'AI se koristi za istraživanje, strukturisanje, pripremu sadržaja, analizu i automatizaciju niskorizičnih operativnih zadataka. AI nije garancija poslovnog rezultata. Novac, ugovori, pravno važne odluke i nejasni ili rizični slučajevi ostaju pod ljudskom kontrolom.':'KI wird für Recherche, Strukturierung, Content-Vorbereitung, Analyse und die Automatisierung risikoarmer operativer Aufgaben eingesetzt. KI ist keine Erfolgsgarantie. Geld, Verträge, rechtlich relevante Entscheidungen sowie unklare oder riskante Fälle bleiben unter menschlicher Kontrolle.'}</p><p>{sr?'Cenovne i tržišne tvrdnje označene kao test predstavljaju hipoteze dok ih ne potvrde stvarne transakcije i podaci.':'Als Test gekennzeichnete Preis- und Marktannahmen bleiben Hypothesen, bis reale Transaktionen und Daten sie bestätigen.'}</p></>}
    <p style={{marginTop:'42px'}}><a href={`/${lang}/`}>← DaniniHub</a></p>
  </main></div>
}