import { useEffect, useMemo, useState } from 'react'
import './TransportRoomDemo.css'

const copy={
 de:{kicker:'DANINIHUB TRANSPORT ROOM · PILOT MVP',title:'Duisburg → Beograd',subtitle:'Ein gemeinsamer operativer Raum mit rollenbasierten Rechten.',demo:'Fiktive Demonstration. Keine reale Transportsteuerung.',choose:'Rolle für den Pilotzugang wählen',roles:{DACH_CUSTOMER:'DACH Auftraggeber',BALKAN_CARRIER:'Balkan Frachtführer',DANINIHUB_OPERATOR:'DaniniHub Operator'},enter:'Pilotzugang öffnen',changeRole:'Rolle wechseln',role:'Aktive Rolle',rights:'Bearbeitungsrechte',readOnly:'Nur Ansicht für diese Rolle',tabs:['Übersicht','Kommunikation','Dokumente','Incident','Abschlussbericht'],status:'Transportstatus',eta:'Operative ETA',nextCheck:'Nächste Prüfung',risk:'Risiko',owner:'Verantwortlich',partner:'Partner',vehicle:'Fahrzeug',driver:'Fahrer',facts:'Bestätigte Fakten',open:'Offene Punkte',timeline:'Statusverlauf',addStatus:'Nächsten Status setzen',message:'Standardisierte Nachricht',source:'Quelle',confirmed:'Manuell freigegeben',translate:'Vorschlag aktualisieren',approve:'Manuell freigeben',noAuto:'Nichts wird automatisch versendet.',docs:'Dokumentenstatus',incident:'Abweichung melden',severity:'Schweregrad',decision:'Erforderliche Entscheidung',escalation:'Eskalieren',report:'Abschlussbericht erstellen',complete:'Transport abschließen',save:'Änderungen speichern',saving:'Speichern…',saved:'Gespeichert',loading:'Fall wird geladen…',loadError:'Der Fall konnte nicht geladen werden.',saveError:'Speichern fehlgeschlagen.',accessError:'Pilotzugang konnte nicht erstellt werden.',storage:'Speicher',present:'Vorhanden',missing:'Fehlt',review:'Zu prüfen'},
 sr:{kicker:'DANINIHUB TRANSPORT ROOM · PILOT MVP',title:'Duisburg → Beograd',subtitle:'Zajednički operativni prostor sa pravima prema ulozi.',demo:'Fiktivna demonstracija. Nije stvarno upravljanje transportom.',choose:'Izaberite ulogu za pilot pristup',roles:{DACH_CUSTOMER:'DACH naručilac',BALKAN_CARRIER:'Balkan prevoznik',DANINIHUB_OPERATOR:'DaniniHub operator'},enter:'Otvori pilot pristup',changeRole:'Promeni ulogu',role:'Aktivna uloga',rights:'Prava izmene',readOnly:'Samo pregled za ovu ulogu',tabs:['Pregled','Komunikacija','Dokumenti','Incident','Završni izveštaj'],status:'Status transporta',eta:'Operativni ETA',nextCheck:'Sledeća provera',risk:'Rizik',owner:'Odgovoran',partner:'Partner',vehicle:'Vozilo',driver:'Vozač',facts:'Potvrđene činjenice',open:'Otvorene tačke',timeline:'Tok statusa',addStatus:'Postavi sledeći status',message:'Standardizovana poruka',source:'Izvor',confirmed:'Ručno odobreno',translate:'Ažuriraj predlog',approve:'Ručno odobri',noAuto:'Ništa se ne šalje automatski.',docs:'Status dokumenata',incident:'Prijavi odstupanje',severity:'Ozbiljnost',decision:'Potrebna odluka',escalation:'Eskaliraj',report:'Kreiraj završni izveštaj',complete:'Završi transport',save:'Sačuvaj izmene',saving:'Čuvam…',saved:'Sačuvano',loading:'Učitavam slučaj…',loadError:'Slučaj nije mogao da se učita.',saveError:'Čuvanje nije uspelo.',accessError:'Pilot pristup nije mogao da se kreira.',storage:'Skladište',present:'Postoji',missing:'Nedostaje',review:'Za proveru'}
}
const statusOrder=['ORDER_RECORDED','IN_TRANSIT','DELAY_RISK','CUSTOMER_INFORMED','ESCALATED','COMPLETED']
const labels={de:{ORDER_RECORDED:'AUFTRAG ERFASST',IN_TRANSIT:'FAHRZEUG UNTERWEGS',DELAY_RISK:'VERZÖGERUNGSRISIKO',CUSTOMER_INFORMED:'KUNDE INFORMIERT',ESCALATED:'ESKALIERT',COMPLETED:'ABGESCHLOSSEN'},sr:{ORDER_RECORDED:'NALOG UNET',IN_TRANSIT:'VOZILO NA PUTU',DELAY_RISK:'RIZIK KAŠNJENJA',CUSTOMER_INFORMED:'KLIJENT OBAVEŠTEN',ESCALATED:'ESKALIRANO',COMPLETED:'ZAVRŠENO'}}
const fieldNames={de:{status:'Status',eta:'ETA',nextCheck:'Prüfzeit',risk:'Risiko',approvedMessage:'Freigabe',standardizedMessage:'Nachricht',vehicle:'Fahrzeug',driver:'Fahrer',documents:'Dokumente',incident:'Incident',timeline:'Verlauf',partner:'Partner',owner:'Verantwortung',route:'Relation'},sr:{status:'Status',eta:'ETA',nextCheck:'Provera',risk:'Rizik',approvedMessage:'Odobrenje',standardizedMessage:'Poruka',vehicle:'Vozilo',driver:'Vozač',documents:'Dokumenti',incident:'Incident',timeline:'Tok',partner:'Partner',owner:'Odgovornost',route:'Relacija'}}

export default function TransportRoomDemo({lang}){
 const t=copy[lang],[tab,setTab]=useState(0),[room,setRoom]=useState(null),[sync,setSync]=useState('idle'),[storage,setStorage]=useState('—'),[role,setRole]=useState(sessionStorage.getItem('tr-role')||''),[token,setToken]=useState(sessionStorage.getItem('tr-token')||''),[permissions,setPermissions]=useState([])
 const can=key=>permissions.includes(key)
 const headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token}`})
 const load=async activeToken=>{setSync('loading');try{const r=await fetch('/api/v1/transport-room/DH-TR-0001',{headers:{Authorization:`Bearer ${activeToken}`}});if(!r.ok)throw new Error();const data=await r.json();setRoom(data.case);setStorage(data.storageMode||'—');setRole(data.role);setPermissions(data.permissions||[]);setSync('idle')}catch{setRoom(null);setSync('load-error')}}
 useEffect(()=>{if(token)load(token)},[])
 const enter=async selected=>{setSync('loading');try{const r=await fetch('/api/v1/transport-room/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({caseId:'DH-TR-0001',role:selected})});if(!r.ok)throw new Error();const data=await r.json();sessionStorage.setItem('tr-token',data.token);sessionStorage.setItem('tr-role',selected);setToken(data.token);setRole(selected);await load(data.token)}catch{setSync('access-error')}}
 const logout=()=>{sessionStorage.removeItem('tr-token');sessionStorage.removeItem('tr-role');setToken('');setRole('');setRoom(null);setPermissions([]);setSync('idle')}
 const timeline=useMemo(()=>room?.timeline||[],[room]),patch=(key,value)=>setRoom(current=>({...current,[key]:value}))
 const save=async()=>{setSync('saving');try{const response=await fetch(`/api/v1/transport-room/${room.caseId}`,{method:'PUT',headers:headers(),body:JSON.stringify(room)});if(!response.ok)throw new Error();const data=await response.json();setRoom(data.case);setPermissions(data.permissions||[]);setStorage(data.storageMode||'—');setSync('saved')}catch{setSync('save-error')}}
 const addStatus=()=>{if(!can('status')||!can('timeline'))return;const current=Math.max(0,statusOrder.indexOf(room.status)),next=statusOrder[Math.min(current+1,statusOrder.length-1)];setRoom(value=>({...value,status:next,timeline:[...(value.timeline||[]),{at:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}),status:next,note:lang==='sr'?'Status ručno ažuriran u Transport Room-u.':'Status im Transport Room manuell aktualisiert.'}]}))}
 const setDoc=(key,value)=>can('documents')&&patch('documents',{...room.documents,[key]:value})
 const input=(key,label)=><div><small>{label}</small><input disabled={!can(key)} value={room[key]} onChange={e=>patch(key,e.target.value)}/></div>
 if(!token)return <main className="tr-shell"><section className="tr-access tr-card"><p className="tr-kicker">{t.kicker}</p><h1>{t.choose}</h1><div className="tr-role-grid">{Object.entries(t.roles).map(([key,label])=><button key={key} onClick={()=>enter(key)}>{label}</button>)}</div>{sync==='access-error'&&<p className="tr-error">{t.accessError}</p>}<small>{t.demo}</small></section></main>
 if(sync==='loading')return <main className="tr-shell"><section className="tr-card"><p>{t.loading}</p></section></main>
 if(!room)return <main className="tr-shell"><section className="tr-card"><p>{t.loadError}</p><button onClick={logout}>{t.changeRole}</button></section></main>
 return <main className="tr-shell">
  <header className="tr-head"><div><p className="tr-kicker">{t.kicker}</p><h1>{t.title}</h1><p>{t.subtitle}</p><p><b>{t.role}:</b> {t.roles[role]}</p></div><div><span className="tr-demo">{t.demo}</span><button onClick={save} disabled={sync==='saving'}>{sync==='saving'?t.saving:t.save}</button><button className="tr-role-change" onClick={logout}>{t.changeRole}</button><small>{t.storage}: {storage} · {sync==='saved'?t.saved:sync==='save-error'?t.saveError:''}</small></div></header>
  <section className="tr-permissions"><b>{t.rights}:</b> {permissions.map(key=>fieldNames[lang][key]||key).join(' · ')}</section>
  <section className="tr-summary"><article><small>{t.status}</small><strong>{labels[lang][room.status]}</strong></article><article><small>{t.eta}</small><input disabled={!can('eta')} value={room.eta} onChange={e=>patch('eta',e.target.value)}/></article><article><small>{t.nextCheck}</small><input disabled={!can('nextCheck')} value={room.nextCheck} onChange={e=>patch('nextCheck',e.target.value)}/></article><article><small>{t.risk}</small><select disabled={!can('risk')} value={room.risk} onChange={e=>patch('risk',e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></article></section>
  <section className="tr-transport-card">{input('partner',t.partner)}{input('vehicle',t.vehicle)}{input('driver',t.driver)}{input('owner',t.owner)}</section>
  <nav className="tr-tabs">{t.tabs.map((label,i)=><button key={label} className={tab===i?'active':''} onClick={()=>setTab(i)}>{label}</button>)}</nav>
  {tab===0&&<section className="tr-grid"><article className="tr-card"><h2>{t.facts}</h2><ul><li>Duisburg loading completed 08:10</li><li>Vehicle passed Nürnberg 12:20</li><li>Driver reported congestion before Budapest</li></ul></article><article className="tr-card"><h2>{t.open}</h2><ul><li>Current GPS position</li><li>Remaining driving time</li><li>Whether unloading slot remains available</li></ul></article><article className="tr-card tr-wide"><h2>{t.timeline}</h2><div className="tr-timeline">{timeline.map((item,i)=><span key={`${item.at}-${i}`}><b>{item.at}</b>{labels[lang][item.status]}<small>{item.note}</small></span>)}</div><button disabled={!can('status')||!can('timeline')} onClick={addStatus}>{t.addStatus}</button></article></section>}
  {tab===1&&<section className="tr-grid"><article className="tr-card"><h2>{t.source}</h2><p>WhatsApp · Fahrer / Vozač · 14:52</p><blockquote>“Stau Budapest. ETA unklar. Kunde wartet.”</blockquote></article><article className="tr-card"><h2>{t.message}</h2><textarea disabled={!can('standardizedMessage')} value={room.standardizedMessage} onChange={e=>patch('standardizedMessage',e.target.value)} rows="8"/><div className="tr-actions"><button disabled={!can('standardizedMessage')} onClick={()=>patch('standardizedMessage',lang==='sr'?'Vozač prijavljuje zastoj pre Budimpešte. Pre pouzdane ETA procene moraju se potvrditi lokacija i preostalo vreme vožnje.':'Der Fahrer meldet Stau vor Budapest. Vor einer belastbaren ETA müssen Standort und Restlenkzeit bestätigt werden.')}>{t.translate}</button><button disabled={!can('approvedMessage')} className="secondary" onClick={()=>patch('approvedMessage',true)}>{t.approve}</button></div><small>{room.approvedMessage?t.confirmed:t.noAuto}</small></article></section>}
  {tab===2&&<section className="tr-card"><h2>{t.docs}</h2><div className="tr-docs">{[['order','Transportauftrag'],['cmr','CMR'],['pod','POD / Abliefernachweis'],['insurance','Versicherung / Osiguranje']].map(([key,name])=><div key={key}><strong>{name}</strong><select disabled={!can('documents')} value={room.documents[key]} onChange={e=>setDoc(key,e.target.value)}><option value="PRESENT">{t.present}</option><option value="REVIEW">{t.review}</option><option value="MISSING">{t.missing}</option></select></div>)}</div></section>}
  {tab===3&&<section className="tr-grid"><article className="tr-card"><h2>{t.incident}</h2><label>{t.severity}<select disabled={!can('incident')} value={room.incident.severity} onChange={e=>patch('incident',{...room.incident,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>{t.decision}<textarea disabled={!can('incident')} value={room.incident.decision} onChange={e=>patch('incident',{...room.incident,decision:e.target.value})} rows="5"/></label><button disabled={!can('incident')} onClick={()=>patch('incident',{...room.incident,status:'ESCALATED'})}>{t.escalation}</button></article><article className="tr-card"><h2>Incident Log</h2>{timeline.filter(item=>['DELAY_RISK','ESCALATED'].includes(item.status)).map((item,i)=><p key={i}><b>{item.at}</b> {item.note}</p>)}<p><b>Status:</b> {room.incident.status}</p></article></section>}
  {tab===4&&<section className="tr-card tr-report"><h2>{t.tabs[4]}</h2><p>{lang==='sr'?'Transport sadrži dokumentovan status, ETA, komunikaciju, dokumente i incident. Završavanje zahteva ljudsku proveru.':'Der Transport enthält dokumentierten Status, ETA, Kommunikation, Dokumente und Incident. Der Abschluss erfordert menschliche Prüfung.'}</p><div className="tr-report-grid"><span><small>Transport</small><b>{room.caseId}</b></span><span><small>Updates</small><b>{timeline.length}</b></span><span><small>Incident</small><b>{room.incident.status}</b></span><span><small>Documents</small><b>{Object.values(room.documents).filter(v=>v==='PRESENT').length} / 4</b></span></div><button disabled={!can('status')} onClick={()=>patch('status','COMPLETED')}>{room.status==='COMPLETED'?t.complete:t.report}</button>{room.status==='COMPLETED'&&<p className="tr-success">REPORT READY · HUMAN REVIEW REQUIRED</p>}</section>}
 </main>
}
