import { useEffect, useMemo, useState } from 'react'
import './TransportRoomDemo.css'

const copy={
 de:{kicker:'DANINIHUB TRANSPORT ROOM · PILOT MVP',title:'Duisburg → Beograd',subtitle:'Gemeinsamer operativer Raum mit Rollen, Einladungen und Sicherheitscode.',demo:'Fiktive Demonstration. Keine reale Transportsteuerung.',choose:'Rolle für den Pilotzugang wählen',roles:{DACH_CUSTOMER:'DACH Auftraggeber',BALKAN_CARRIER:'Balkan Frachtführer',DANINIHUB_OPERATOR:'DaniniHub Operator'},changeRole:'Zugang wechseln',role:'Aktive Rolle',identity:'Identität',rights:'Bearbeitungsrechte',tabs:['Übersicht','Kommunikation','Dokumente','Incident','Abschlussbericht'],status:'Transportstatus',eta:'Operative ETA',nextCheck:'Nächste Prüfung',risk:'Risiko',owner:'Verantwortlich',partner:'Partner',vehicle:'Fahrzeug',driver:'Fahrer',facts:'Bestätigte Fakten',open:'Offene Punkte',timeline:'Statusverlauf',addStatus:'Nächsten Status setzen',message:'Standardisierte Nachricht',source:'Quelle',confirmed:'Manuell freigegeben',translate:'Vorschlag aktualisieren',approve:'Manuell freigeben',noAuto:'Nichts wird automatisch versendet.',docs:'Dokumentenstatus',incident:'Abweichung melden',severity:'Schweregrad',decision:'Erforderliche Entscheidung',escalation:'Eskalieren',report:'Abschlussbericht erstellen',complete:'Transport abschließen',save:'Änderungen speichern',saving:'Speichern…',saved:'Gespeichert',loading:'Fall wird geladen…',loadError:'Der Fall konnte nicht geladen werden.',saveError:'Speichern fehlgeschlagen.',accessError:'Zugang konnte nicht erstellt werden.',storage:'Speicher',present:'Vorhanden',missing:'Fehlt',review:'Zu prüfen',inviteTitle:'Partner einladen',name:'Name',email:'E-Mail',inviteRole:'Rolle',validity:'Gültigkeit',hours:'Stunden',sendInvite:'Einladung erstellen',inviteReady:'Einladung erstellt',inviteSent:'E-Mail wurde versendet.',inviteCopy:'Link kopieren',inviteError:'Einladung konnte nicht erstellt werden.',codeTitle:'Sicherheitscode eingeben',codeInfo:'Ein sechsstelliger Code wurde an',verify:'Code prüfen',wrongCode:'Code ist falsch oder abgelaufen.',invites:'Einladungen',audit:'Audit-Protokoll',refresh:'Aktualisieren',revoke:'Zugang widerrufen',used:'VERWENDET',active:'AKTIV',revoked:'WIDERRUFEN',noItems:'Noch keine Einträge.'},
 sr:{kicker:'DANINIHUB TRANSPORT ROOM · PILOT MVP',title:'Duisburg → Beograd',subtitle:'Zajednički operativni prostor sa ulogama, pozivnicama i sigurnosnim kodom.',demo:'Fiktivna demonstracija. Nije stvarno upravljanje transportom.',choose:'Izaberite ulogu za pilot pristup',roles:{DACH_CUSTOMER:'DACH naručilac',BALKAN_CARRIER:'Balkan prevoznik',DANINIHUB_OPERATOR:'DaniniHub operator'},changeRole:'Promeni pristup',role:'Aktivna uloga',identity:'Identitet',rights:'Prava izmene',tabs:['Pregled','Komunikacija','Dokumenti','Incident','Završni izveštaj'],status:'Status transporta',eta:'Operativni ETA',nextCheck:'Sledeća provera',risk:'Rizik',owner:'Odgovoran',partner:'Partner',vehicle:'Vozilo',driver:'Vozač',facts:'Potvrđene činjenice',open:'Otvorene tačke',timeline:'Tok statusa',addStatus:'Postavi sledeći status',message:'Standardizovana poruka',source:'Izvor',confirmed:'Ručno odobreno',translate:'Ažuriraj predlog',approve:'Ručno odobri',noAuto:'Ništa se ne šalje automatski.',docs:'Status dokumenata',incident:'Prijavi odstupanje',severity:'Ozbiljnost',decision:'Potrebna odluka',escalation:'Eskaliraj',report:'Kreiraj završni izveštaj',complete:'Završi transport',save:'Sačuvaj izmene',saving:'Čuvam…',saved:'Sačuvano',loading:'Učitavam slučaj…',loadError:'Slučaj nije mogao da se učita.',saveError:'Čuvanje nije uspelo.',accessError:'Pristup nije mogao da se kreira.',storage:'Skladište',present:'Postoji',missing:'Nedostaje',review:'Za proveru',inviteTitle:'Pozovi partnera',name:'Ime',email:'E-mail',inviteRole:'Uloga',validity:'Važenje',hours:'sati',sendInvite:'Kreiraj pozivnicu',inviteReady:'Pozivnica je kreirana',inviteSent:'E-mail je poslat.',inviteCopy:'Kopiraj link',inviteError:'Pozivnica nije mogla da se kreira.',codeTitle:'Unesite sigurnosni kod',codeInfo:'Šestocifreni kod je poslat na',verify:'Proveri kod',wrongCode:'Kod nije tačan ili je istekao.',invites:'Pozivnice',audit:'Audit evidencija',refresh:'Osveži',revoke:'Opozovi pristup',used:'ISKORIŠĆENA',active:'AKTIVNA',revoked:'OPOZVANA',noItems:'Još nema zapisa.'}
}
const statusOrder=['ORDER_RECORDED','IN_TRANSIT','DELAY_RISK','CUSTOMER_INFORMED','ESCALATED','COMPLETED']
const labels={de:{ORDER_RECORDED:'AUFTRAG ERFASST',IN_TRANSIT:'FAHRZEUG UNTERWEGS',DELAY_RISK:'VERZÖGERUNGSRISIKO',CUSTOMER_INFORMED:'KUNDE INFORMIERT',ESCALATED:'ESKALIERT',COMPLETED:'ABGESCHLOSSEN'},sr:{ORDER_RECORDED:'NALOG UNET',IN_TRANSIT:'VOZILO NA PUTU',DELAY_RISK:'RIZIK KAŠNJENJA',CUSTOMER_INFORMED:'KLIJENT OBAVEŠTEN',ESCALATED:'ESKALIRANO',COMPLETED:'ZAVRŠENO'}}
const fieldNames={de:{status:'Status',eta:'ETA',nextCheck:'Prüfzeit',risk:'Risiko',approvedMessage:'Freigabe',standardizedMessage:'Nachricht',vehicle:'Fahrzeug',driver:'Fahrer',documents:'Dokumente',incident:'Incident',timeline:'Verlauf',partner:'Partner',owner:'Verantwortung',route:'Relation'},sr:{status:'Status',eta:'ETA',nextCheck:'Provera',risk:'Rizik',approvedMessage:'Odobrenje',standardizedMessage:'Poruka',vehicle:'Vozilo',driver:'Vozač',documents:'Dokumenti',incident:'Incident',timeline:'Tok',partner:'Partner',owner:'Odgovornost',route:'Relacija'}}

export default function TransportRoomDemo({lang}){
 const t=copy[lang]
 const [tab,setTab]=useState(0),[room,setRoom]=useState(null),[sync,setSync]=useState('idle'),[storage,setStorage]=useState('—')
 const [role,setRole]=useState(sessionStorage.getItem('tr-role')||''),[identity,setIdentity]=useState(sessionStorage.getItem('tr-identity')||''),[token,setToken]=useState(sessionStorage.getItem('tr-token')||''),[permissions,setPermissions]=useState([])
 const [invite,setInvite]=useState(null),[inviteState,setInviteState]=useState('idle'),[challenge,setChallenge]=useState(null),[otpError,setOtpError]=useState(false)
 const [invitations,setInvitations]=useState([]),[audit,setAudit]=useState([])
 const can=key=>permissions.includes(key)
 const headers=active=>({'Content-Type':'application/json','Authorization':`Bearer ${active||token}`})
 const load=async activeToken=>{setSync('loading');try{const r=await fetch('/api/v1/transport-room/DH-TR-0001',{headers:{Authorization:`Bearer ${activeToken}`}});if(!r.ok)throw new Error();const data=await r.json();setRoom(data.case);setStorage(data.storageMode||'—');setRole(data.role);setIdentity(data.identity||'demo-user');setPermissions(data.permissions||[]);sessionStorage.setItem('tr-role',data.role);sessionStorage.setItem('tr-identity',data.identity||'demo-user');setSync('idle')}catch{setRoom(null);setSync('load-error')}}
 const startInvite=async inviteToken=>{setSync('loading');try{const r=await fetch('/api/v1/transport-room/invitations/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:inviteToken})});if(!r.ok)throw new Error();const data=await r.json();setChallenge(data);history.replaceState({},'',location.pathname);setSync('idle')}catch{setSync('access-error')}}
 useEffect(()=>{const inviteToken=new URLSearchParams(location.search).get('invite');if(inviteToken){startInvite(inviteToken);return}if(token)load(token)},[])
 const enter=async selected=>{setSync('loading');try{const r=await fetch('/api/v1/transport-room/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({caseId:'DH-TR-0001',role:selected})});if(!r.ok)throw new Error();const data=await r.json();sessionStorage.setItem('tr-token',data.token);setToken(data.token);await load(data.token)}catch{setSync('access-error')}}
 const verifyOtp=async e=>{e.preventDefault();setOtpError(false);const code=new FormData(e.currentTarget).get('code');try{const r=await fetch('/api/v1/transport-room/invitations/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challengeId:challenge.challengeId,code})});if(!r.ok)throw new Error();const data=await r.json();sessionStorage.setItem('tr-token',data.token);setToken(data.token);setChallenge(null);await load(data.token)}catch{setOtpError(true)}}
 const logout=()=>{['tr-token','tr-role','tr-identity'].forEach(key=>sessionStorage.removeItem(key));setToken('');setRole('');setIdentity('');setRoom(null);setPermissions([]);setSync('idle')}
 const timeline=useMemo(()=>room?.timeline||[],[room]),patch=(key,value)=>setRoom(current=>({...current,[key]:value}))
 const save=async()=>{setSync('saving');try{const response=await fetch(`/api/v1/transport-room/${room.caseId}`,{method:'PUT',headers:headers(),body:JSON.stringify(room)});if(!response.ok)throw new Error();const data=await response.json();setRoom(data.case);setPermissions(data.permissions||[]);setStorage(data.storageMode||'—');setSync('saved')}catch{setSync('save-error')}}
 const addStatus=()=>{if(!can('status')||!can('timeline'))return;const current=Math.max(0,statusOrder.indexOf(room.status)),next=statusOrder[Math.min(current+1,statusOrder.length-1)];setRoom(value=>({...value,status:next,timeline:[...(value.timeline||[]),{at:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}),status:next,note:lang==='sr'?'Status ručno ažuriran u Transport Room-u.':'Status im Transport Room manuell aktualisiert.',actor:identity,role}]}))}
 const createInvite=async e=>{e.preventDefault();setInviteState('sending');const form=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch(`/api/v1/transport-room/${room.caseId}/invitations`,{method:'POST',headers:headers(),body:JSON.stringify(form)});if(!r.ok)throw new Error();const data=await r.json();setInvite(data);setInviteState('ready');await loadAdmin()}catch{setInviteState('error')}}
 const loadAdmin=async()=>{if(role!=='DANINIHUB_OPERATOR')return;const [ir,ar]=await Promise.all([fetch(`/api/v1/transport-room/${room.caseId}/invitations`,{headers:headers()}),fetch(`/api/v1/transport-room/${room.caseId}/audit`,{headers:headers()})]);if(ir.ok)setInvitations((await ir.json()).invitations||[]);if(ar.ok)setAudit((await ar.json()).events||[])}
 useEffect(()=>{if(room&&role==='DANINIHUB_OPERATOR')loadAdmin()},[room?.caseId,role])
 const revoke=async id=>{const r=await fetch(`/api/v1/transport-room/${room.caseId}/invitations/${id}/revoke`,{method:'POST',headers:headers()});if(r.ok)loadAdmin()}
 const setDoc=(key,value)=>can('documents')&&patch('documents',{...room.documents,[key]:value})
 const input=(key,label)=><div><small>{label}</small><input disabled={!can(key)} value={room[key]} onChange={e=>patch(key,e.target.value)}/></div>

 if(challenge)return <main className="tr-shell"><section className="tr-access tr-card"><p className="tr-kicker">{t.kicker}</p><h1>{t.codeTitle}</h1><p>{t.codeInfo} <b>{challenge.emailMasked}</b></p><form className="tr-otp" onSubmit={verifyOtp}><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required autoFocus/><button>{t.verify}</button></form>{otpError&&<p className="tr-error">{t.wrongCode}</p>}</section></main>
 if(!token)return <main className="tr-shell"><section className="tr-access tr-card"><p className="tr-kicker">{t.kicker}</p><h1>{t.choose}</h1><div className="tr-role-grid">{Object.entries(t.roles).map(([key,label])=><button key={key} onClick={()=>enter(key)}>{label}</button>)}</div>{sync==='access-error'&&<p className="tr-error">{t.accessError}</p>}<small>{t.demo}</small></section></main>
 if(sync==='loading')return <main className="tr-shell"><section className="tr-card"><p>{t.loading}</p></section></main>
 if(!room)return <main className="tr-shell"><section className="tr-card"><p>{t.loadError}</p><button onClick={logout}>{t.changeRole}</button></section></main>
 return <main className="tr-shell">
  <header className="tr-head"><div><p className="tr-kicker">{t.kicker}</p><h1>{t.title}</h1><p>{t.subtitle}</p><p><b>{t.role}:</b> {t.roles[role]} · <b>{t.identity}:</b> {identity}</p></div><div><span className="tr-demo">{t.demo}</span><button onClick={save} disabled={sync==='saving'}>{sync==='saving'?t.saving:t.save}</button><button className="tr-role-change" onClick={logout}>{t.changeRole}</button><small>{t.storage}: {storage} · {sync==='saved'?t.saved:sync==='save-error'?t.saveError:''}</small></div></header>
  <section className="tr-permissions"><b>{t.rights}:</b> {permissions.map(key=>fieldNames[lang][key]||key).join(' · ')}</section>
  {role==='DANINIHUB_OPERATOR'&&<><section className="tr-card tr-invite"><h2>{t.inviteTitle}</h2><form onSubmit={createInvite}><label>{t.name}<input name="name" maxLength="120"/></label><label>{t.email}<input name="email" type="email" required/></label><label>{t.inviteRole}<select name="role" defaultValue="BALKAN_CARRIER"><option value="BALKAN_CARRIER">{t.roles.BALKAN_CARRIER}</option><option value="DACH_CUSTOMER">{t.roles.DACH_CUSTOMER}</option></select></label><label>{t.validity}<select name="hours" defaultValue="48"><option value="24">24 {t.hours}</option><option value="48">48 {t.hours}</option><option value="72">72 {t.hours}</option><option value="168">168 {t.hours}</option></select></label><button>{t.sendInvite}</button></form>{inviteState==='error'&&<p className="tr-error">{t.inviteError}</p>}{inviteState==='ready'&&<div className="tr-invite-result"><b>{t.inviteReady}</b><input readOnly value={invite.invitation.link}/><button onClick={()=>navigator.clipboard?.writeText(invite.invitation.link)}>{t.inviteCopy}</button><small>{invite.delivery?.sent?t.inviteSent:invite.delivery?.reason||''}</small></div>}</section><section className="tr-admin-grid"><article className="tr-card"><h2>{t.invites}</h2><button onClick={loadAdmin}>{t.refresh}</button>{invitations.length?invitations.map(i=><div className="tr-admin-row" key={i.inviteId}><div><b>{i.email}</b><small>{t.roles[i.role]} · {i.status}</small></div>{i.status==='ACTIVE'&&<button onClick={()=>revoke(i.inviteId)}>{t.revoke}</button>}</div>):<p>{t.noItems}</p>}</article><article className="tr-card"><h2>{t.audit}</h2>{audit.length?audit.slice(0,20).map(e=><div className="tr-audit-row" key={e.id}><b>{e.action}</b><span>{e.identity} · {e.role}</span><small>{new Date(e.at).toLocaleString()}</small></div>):<p>{t.noItems}</p>}</article></section></>}
  <section className="tr-summary"><article><small>{t.status}</small><strong>{labels[lang][room.status]}</strong></article><article><small>{t.eta}</small><input disabled={!can('eta')} value={room.eta} onChange={e=>patch('eta',e.target.value)}/></article><article><small>{t.nextCheck}</small><input disabled={!can('nextCheck')} value={room.nextCheck} onChange={e=>patch('nextCheck',e.target.value)}/></article><article><small>{t.risk}</small><select disabled={!can('risk')} value={room.risk} onChange={e=>patch('risk',e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></article></section>
  <section className="tr-transport-card">{input('partner',t.partner)}{input('vehicle',t.vehicle)}{input('driver',t.driver)}{input('owner',t.owner)}</section>
  <nav className="tr-tabs">{t.tabs.map((label,i)=><button key={label} className={tab===i?'active':''} onClick={()=>setTab(i)}>{label}</button>)}</nav>
  {tab===0&&<section className="tr-grid"><article className="tr-card"><h2>{t.facts}</h2><ul><li>Duisburg loading completed 08:10</li><li>Vehicle passed Nürnberg 12:20</li><li>Driver reported congestion before Budapest</li></ul></article><article className="tr-card"><h2>{t.open}</h2><ul><li>Current GPS position</li><li>Remaining driving time</li><li>Whether unloading slot remains available</li></ul></article><article className="tr-card tr-wide"><h2>{t.timeline}</h2><div className="tr-timeline">{timeline.map((item,i)=><span key={`${item.at}-${i}`}><b>{item.at}</b>{labels[lang][item.status]}<small>{item.note}{item.actor?` · ${item.actor}`:''}</small></span>)}</div><button disabled={!can('status')||!can('timeline')} onClick={addStatus}>{t.addStatus}</button></article></section>}
  {tab===1&&<section className="tr-grid"><article className="tr-card"><h2>{t.source}</h2><p>WhatsApp · Fahrer / Vozač · 14:52</p><blockquote>“Stau Budapest. ETA unklar. Kunde wartet.”</blockquote></article><article className="tr-card"><h2>{t.message}</h2><textarea disabled={!can('standardizedMessage')} value={room.standardizedMessage} onChange={e=>patch('standardizedMessage',e.target.value)} rows="8"/><div className="tr-actions"><button disabled={!can('standardizedMessage')} onClick={()=>patch('standardizedMessage',lang==='sr'?'Vozač prijavljuje zastoj pre Budimpešte. Pre pouzdane ETA procene moraju se potvrditi lokacija i preostalo vreme vožnje.':'Der Fahrer meldet Stau vor Budapest. Vor einer belastbaren ETA müssen Standort und Restlenkzeit bestätigt werden.')}>{t.translate}</button><button disabled={!can('approvedMessage')} className="secondary" onClick={()=>patch('approvedMessage',true)}>{t.approve}</button></div><small>{room.approvedMessage?t.confirmed:t.noAuto}</small></article></section>}
  {tab===2&&<section className="tr-card"><h2>{t.docs}</h2><div className="tr-docs">{[['order','Transportauftrag'],['cmr','CMR'],['pod','POD / Abliefernachweis'],['insurance','Versicherung / Osiguranje']].map(([key,name])=><div key={key}><strong>{name}</strong><select disabled={!can('documents')} value={room.documents[key]} onChange={e=>setDoc(key,e.target.value)}><option value="PRESENT">{t.present}</option><option value="REVIEW">{t.review}</option><option value="MISSING">{t.missing}</option></select></div>)}</div></section>}
  {tab===3&&<section className="tr-grid"><article className="tr-card"><h2>{t.incident}</h2><label>{t.severity}<select disabled={!can('incident')} value={room.incident.severity} onChange={e=>patch('incident',{...room.incident,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>{t.decision}<textarea disabled={!can('incident')} value={room.incident.decision} onChange={e=>patch('incident',{...room.incident,decision:e.target.value})} rows="5"/></label><button disabled={!can('incident')} onClick={()=>patch('incident',{...room.incident,status:'ESCALATED'})}>{t.escalation}</button></article><article className="tr-card"><h2>Incident Log</h2>{timeline.filter(item=>['DELAY_RISK','ESCALATED'].includes(item.status)).map((item,i)=><p key={i}><b>{item.at}</b> {item.note}</p>)}<p><b>Status:</b> {room.incident.status}</p></article></section>}
  {tab===4&&<section className="tr-card tr-report"><h2>{t.tabs[4]}</h2><p>{lang==='sr'?'Transport sadrži dokumentovan status, ETA, komunikaciju, dokumente i incident. Završavanje zahteva ljudsku proveru.':'Der Transport enthält dokumentierten Status, ETA, Kommunikation, Dokumente und Incident. Der Abschluss erfordert menschliche Prüfung.'}</p><div className="tr-report-grid"><span><small>Transport</small><b>{room.caseId}</b></span><span><small>Updates</small><b>{timeline.length}</b></span><span><small>Incident</small><b>{room.incident.status}</b></span><span><small>Documents</small><b>{Object.values(room.documents).filter(v=>v==='PRESENT').length} / 4</b></span></div><button disabled={!can('status')} onClick={()=>patch('status','COMPLETED')}>{room.status==='COMPLETED'?t.complete:t.report}</button></section>}
 </main>
}
